sudo: false

language: php

php:
  - 5.5
  - 5.6

before_script:
  - mkdir -p build/logs

install:
  - composer install --prefer-dist

script:
  - bin/phpunit -c app/ --coverage-clover build/logs/clover.xml
  - bin/phpunit -c app/ --group functional

after_success:
  - bin/coveralls -v
